[mypy]
python_version = 3.11
strict = True
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
exclude = venv|\.git|__pycache__|\.pytest_cache

[mypy-src.api.routers.collection]
disallow_untyped_defs = True
check_untyped_defs = True
