// Generated by scripts/export_input_limits.py. Do not edit manually.
export const INPUT_LIMITS = {
  "name": 50,
  "lifeVision": 500,
  "feedback": 500,
  "customAction": 500,
  "storyDialogue": 2000,
  "rewriteInstruction": 2000,
  "replacementSegment": 12000,
  "fullStory": 32000,
  "voiceText": 32000,
  "characterSettingsBytes": 262144
} as const;

export type InputLimitName = keyof typeof INPUT_LIMITS;
