#!/usr/bin/env python3
"""Generate the frontend input-limit constants from the backend registry."""

from __future__ import annotations

import json
import os
import sys

project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, project_root)

from src.api.input_limits import PUBLIC_INPUT_LIMITS  # noqa: E402


def render_typescript() -> str:
    payload = json.dumps(PUBLIC_INPUT_LIMITS, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/export_input_limits.py. Do not edit manually.\n"
        f"export const INPUT_LIMITS = {payload} as const;\n\n"
        "export type InputLimitName = keyof typeof INPUT_LIMITS;\n"
    )


def main() -> None:
    output_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        project_root, "frontend", "src", "types", "input-limits.generated.ts"
    )
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as output_file:
        output_file.write(render_typescript())
    print(f"Input limits exported to: {output_path}")


if __name__ == "__main__":
    main()
